/**
 * T46：已核對讀音與重音句界的音檔覆寫；不由孤立詞重音推斷整句重音。
 * 重音型參考 Kanjium（Uros O.），commit 6f32ef33701e572f5485f85eda7ffb9333f8c24e。
 * 本檔重音資料依 CC BY-SA 4.0 提供：https://creativecommons.org/licenses/by-sa/4.0/
 * https://github.com/mifunetoshiro/kanjium/blob/6f32ef33701e572f5485f85eda7ffb9333f8c24e/data/source_files/raw/accents.txt
 * kana 為 VOICEVOX AquesTalk 風記法，' 標示下降位置，/ 為無停頓句界。
 */

/** @type {Record<string, {text: string, reading: string, kana: string, reason: string, reference: 'kanjium' | 'voicevox'}>} */
export const AUDIO_PROSODY = {
  'audio/stage-0/day1/vocab-nanijin.mp3': {
    text: '何人',
    reading: 'なにじん',
    kana: "ナニ'ジン",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day2/vocab-nihon.mp3': {
    text: '日本',
    reading: 'にほん',
    kana: "ニホ'ン",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day2/gram-3-1.mp3': {
    text: 'これは何ですか。',
    reading: 'これは なんですか。',
    kana: "コレワ'/ナ'ンデ_スカ",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day2/gram-3-2.mp3': {
    text: 'あれは何ですか。',
    reading: 'あれは なんですか。',
    kana: "アレワ'/ナ'ンデ_スカ",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day2/dlg-1.mp3': {
    text: 'あのう、それは何ですか。',
    reading: 'あのう、それは なんですか。',
    kana: "アノ'ウ、ソレワ'/ナ'ンデ_スカ",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day2/dlg-9.mp3': {
    text: 'はい、そうです。日本のコーヒーです。',
    reading: 'はい、そうです。にほんの コーヒーです。',
    kana: "ハ'イ、ソオデ_ス'、ニホ'ンノ/コオヒ'イデ_ス",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day3/gram-e557b36876.mp3': {
    text: '日本のカメラです。',
    reading: 'にほんの カメラです。',
    kana: "ニホ'ンノ/カ'メラデ_ス",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day3/gram-0966a348aa.mp3': {
    text: 'ここは日本の大使館です。',
    reading: 'ここは にほんの たいしかんです。',
    kana: "ココワ'/ニホ'ンノ/タイシ'カンデ_ス",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day4/vocab-eafc2738fc.mp3': {
    text: '四',
    reading: 'し',
    kana: "シ'",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day4/vocab-afd42f5e48.mp3': {
    text: '七',
    reading: 'しち',
    kana: "_シチ'",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day4/vocab-655c23d926.mp3': {
    text: '分',
    reading: 'ふん',
    kana: "フ'ン",
    reason: '獨立單字採用 Kanjium 收錄的第一個重音型',
    reference: 'kanjium',
  },
  'audio/stage-0/day5/vocab-464bc05184.mp3': {
    text: '一日',
    reading: 'ついたち',
    kana: "ツイタチ'",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day8/vocab-c1cad2a2b6.mp3': {
    text: '辛い',
    reading: 'からい',
    kana: "カラ'イ",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day8/vocab-ea39c25470.mp3': {
    text: '静か',
    reading: 'しずか',
    kana: "シ'ズカ",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day11/vocab-3e3a468f49.mp3': {
    text: '年',
    reading: 'ねん',
    kana: "ネ'ン",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day11/gram-571f4aab77.mp3': {
    text: '駅まで歩いて十分かかります。',
    reading: 'えきまで あるいて じゅっぷん かかります。',
    kana: "エ'キマデ/アル'イテ/ジュッ'プン/カカリマ'_ス",
    reason: '時間的十分以 10分解析，保留數詞與助數詞的連接',
    reference: 'voicevox',
  },
  'audio/stage-0/day11/gram-403425683e.mp3': {
    text: '去年、日本へ来ました。',
    reading: 'きょねん、にほんへ きました。',
    kana: "キョ'ネン、ニホ'ンエ/キマ'_シタ",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day12/gram-3d64dcd286.mp3': {
    text: '日本でどこがいちばん有名ですか。',
    reading: 'にほんで どこが いちばん ゆうめいですか。',
    kana: "ニホ'ンデ/ド'コガ/イチバン'/ユウメエデ'_スカ",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day12/gram-ae7d66f27a.mp3': {
    text: '明日は雨が降ります。',
    reading: 'あしたは あめが ふります。',
    kana: "ア_シタ'ワ/ア'メガ/フリマ'_ス",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day13/gram-ae94d1868b.mp3': {
    text: '私は日本へ行きたいです。',
    reading: 'わたしは にほんへ いきたいです。',
    kana: "ワタシワ'/ニホ'ンエ/イ_キタ'イデ_ス",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day13/gram-c844c661aa.mp3': {
    text: '友達が日本から遊びに来ます。',
    reading: 'ともだちが にほんから あそびに きます。',
    kana: "トモダチガ'/ニホ'ンカラ/アソビニ'/キマ'_ス",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day13/gram-0c62b14d07.mp3': {
    text: '何色のセーターがいいですか。',
    reading: 'なにいろの セーターが いいですか。',
    kana: "ナ'/ニイロノ'/セ'エタアガ/イ'イデ_スカ",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day14/vocab-e46af77952.mp3': {
    text: '角',
    reading: 'かど',
    kana: "カ'ド",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day14/dlg-b878c8b158.mp3': {
    text: 'いいえ、歩いて十分ぐらいです。地図を見せましょうか。',
    reading: 'いいえ、あるいて じゅっぷんぐらいです。ちずを みせましょうか。',
    kana: "イイエ'、アル'イテ/ジュップング'ライデ_ス、チ'ズオ/ミセマショ'オカ",
    reason: '時間的十分以 10分解析，保留數詞與助數詞的連接',
    reference: 'voicevox',
  },
  'audio/stage-0/day15/gram-61b3d08d14.mp3': {
    text: 'お仕事は何ですか。',
    reading: 'おしごとは なんですか。',
    kana: "オシ'ゴトワ/ナ'ンデ_スカ",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day17/vocab-b3ca164985.mp3': {
    text: '丈夫',
    reading: 'じょうぶ',
    kana: "ジョオブ'",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day18/gram-edc2aaec11.mp3': {
    text: '趣味は何ですか。',
    reading: 'しゅみは なんですか。',
    kana: "シュ'ミワ/ナ'ンデ_スカ",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day18/gram-7de4ebddf0.mp3': {
    text: '三日前に日本へ来ました。',
    reading: 'みっかまえに にほんへ きました。',
    kana: "ミッカ'/マ'エニ/ニホ'ンエ/キマ'_シタ",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day18/gram-99f724cffc.mp3': {
    text: '初めて日本へ来ました。',
    reading: 'はじめて にほんへ きました。',
    kana: "ハジ'メテ/ニホ'ンエ/キマ'_シタ",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day18/dlg-6e3d01793e.mp3': {
    text: '田中さんの趣味は何ですか。',
    reading: 'たなかさんの しゅみは なんですか。',
    kana: "タナカサンノ'/シュ'ミワ/ナ'ンデ_スカ",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day19/vocab-2f84000a9e.mp3': {
    text: '二十歳',
    reading: 'はたち',
    kana: "ハ'タチ",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day19/vocab-f1522a24ad.mp3': {
    text: '暇',
    reading: 'ひま',
    kana: "ヒマ'",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day19/vocab-a652545274.mp3': {
    text: '昨夜',
    reading: 'ゆうべ',
    kana: "ユウベ'",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day19/vocab-f9be6008f9.mp3': {
    text: '一昨年',
    reading: 'おととし',
    kana: "オト'トシ",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day19/vocab-9b49d08af1.mp3': {
    text: '晴れる',
    reading: 'はれる',
    kana: "ハレ'ル",
    reason: '獨立單字採用 Kanjium 收錄的第一個重音型',
    reference: 'kanjium',
  },
  'audio/stage-0/day19/gram-c6c7e820b8.mp3': {
    text: '日本の映画を見たことがありますか。',
    reading: 'にほんの えいがを みた ことが ありますか。',
    kana: "ニホ'ンノ/エエガオ'/ミ'タ/コト'ガ/アリマ'_スカ",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day19/gram-d74680227a.mp3': {
    text: '昨夜は早く寝ました。',
    reading: 'ゆうべは はやく ねました。',
    kana: "ユウベワ'/ハヤクネマ'_シタ",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day19/gram-534a1ac085.mp3': {
    text: '夕方、雨が降りました。',
    reading: 'ゆうがた、あめが ふりました。',
    kana: "ユウガタ'、ア'メガ/フリマ'_シタ",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day19/gram-b41ee6efeb.mp3': {
    text: '再来年、二十歳になります。',
    reading: 'さらいねん、はたちに なります。',
    kana: "サライネン'、ハ'タチニ/ナリマ'_ス",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day20/dlg-a24a06adf0.mp3': {
    text: 'ねえ、明日、暇？',
    reading: 'ねえ、あした、ひま？',
    kana: "ネ'エ、ア_シタ'、ヒマ'？",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day21/gram-8046080653.mp3': {
    text: 'これは日本語で何と言いますか。',
    reading: 'これは にほんごで なんと いいますか。',
    kana: "コレワ'/ニホンゴデ'/ナ'ント/イイマ'_スカ",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day21/dlg-06e4a1720a.mp3': {
    text: 'いいえ、まだ見ていません。何と言いましたか。',
    reading: 'いいえ、まだ みて いません。なんと いいましたか。',
    kana: "イイエ'、マ'ダ/ミ'テ/イマセ'ン、ナ'ント/イイマ'_シタカ",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day22/gram-52bb64dbe4.mp3': {
    text: 'ミコさんが好きな食べ物は何ですか。',
    reading: 'ミコさんが すきな たべものは なんですか。',
    kana: "ミ'コサンガ/_スキ'ナ/タベモ'ノワ/ナ'ンデ_スカ",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day22/gram-431eab3ac3.mp3': {
    text: '日本へ行く日は来週です。',
    reading: 'にほんへ いく ひは らいしゅうです。',
    kana: "ニホ'ンエ/イ_ク'/ヒワ'/ライシュウデ'_ス",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day23/vocab-fd0dc4d9bb.mp3': {
    text: '黄色',
    reading: 'きいろ',
    kana: "キイロ'",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day23/vocab-fa4e8cc20b.mp3': {
    text: '開く',
    reading: 'あく',
    kana: "アク'",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day23/gram-139078cbca.mp3': {
    text: '日本へ行ったとき、写真を撮りました。',
    reading: 'にほんへ いった とき、しゃしんを とりました。',
    kana: "ニホ'ンエ/イッタ'/ト'キ、シャシンオ'/トリマ'_シタ",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day23/gram-415ea5fe7f.mp3': {
    text: 'このボタンを押すと、ドアが開きます。',
    reading: 'この ボタンを おすと、ドアが あきます。',
    kana: "コノ'/ボタンオ'/オ_スト'、ド'アガ/アキマ'_ス",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day23/gram-1b68c8135f.mp3': {
    text: 'ドアが開きます。',
    reading: 'ドアが あきます。',
    kana: "ド'アガ/アキマ'_ス",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day23/gram-84114d4553.mp3': {
    text: '窓が開いています。',
    reading: 'まどが あいて います。',
    kana: "マ'ドガ/ア'イテ/イマ'_ス",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day23/gram-6669576b23.mp3': {
    text: '飲み物は何にしますか。',
    reading: 'のみものは なんに しますか。',
    kana: "ノミ'モノワ/ナ'ンニ/シマ'_スカ",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day23/dlg-1c2f474ba5.mp3': {
    text: 'いいですね。何の肉ですか。',
    reading: 'いいですね。なんの にくですか。',
    kana: "イ'イデ_スネ、ナ'ンノ/ニク'デ_スカ",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day23/dlg-296c83ea53.mp3': {
    text: 'そうですか。飲み物は何にしますか。',
    reading: 'そうですか。のみものは なんに しますか。',
    kana: "ソオデ_ス'カ、ノミ'モノワ/ナ'ンニ/シマ'_スカ",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day23/dlg-2d48b40e39.mp3': {
    text: 'ええ。あのドアが開いていますね。閉めましょうか。',
    reading: 'ええ。あの ドアが あいて いますね。しめましょうか。',
    kana: "エ'エ、アノ'/ド'アガ/ア'イテ/イマ'_スネ、シメマショ'オカ",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day24/vocab-87cc62aa66.mp3': {
    text: '方',
    reading: 'かた',
    kana: "カタ'",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day24/vocab-d1747882d7.mp3': {
    text: '辺',
    reading: 'へん',
    kana: "ヘン'",
    reason: '獨立單字採用 Kanjium 收錄的第一個重音型',
    reference: 'kanjium',
  },
  'audio/stage-0/day24/gram-f88e0021cd.mp3': {
    text: 'この辺はいい所ですね。',
    reading: 'この へんは いい ところですね。',
    kana: "コノ'/ヘンワ'/イ'イ/トコロデ'_スネ",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day24/gram-646fd36410.mp3': {
    text: 'あの方は先生です。',
    reading: 'あの かたは せんせいです。',
    kana: "アノ'/カタ'ワ/センセ'エデ_ス",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day24/dlg-9070e166e0.mp3': {
    text: 'この辺はいい所ですね。',
    reading: 'この へんは いい ところですね。',
    kana: "コノ'/ヘンワ'/イ'イ/トコロデ'_スネ",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day24/dlg-92328cfe0b.mp3': {
    text: '田中さんはいい方ですね。',
    reading: 'たなかさんは いい かたですね。',
    kana: "タナカサンワ'/イ'イ/カタ'デ_スネ",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day25/vocab-1bd72cfe9f.mp3': {
    text: '温い',
    reading: 'ぬるい',
    kana: "ヌル'イ",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-0/day25/gram-329a668d77.mp3': {
    text: '日本語を勉強してから、日本へ行きたいです。',
    reading: 'にほんごを べんきょうして から、にほんへ いきたいです。',
    kana: "ニホンゴオ'/ベンキョオ'/_シテカラ'、ニホ'ンエ/イ_キタ'イデ_ス",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-2/quotes/genshin-raiden.mp3': {
    text: '稲光、すなわち永遠なり。',
    reading: 'いなびかり、すなわち えいえん なり。',
    kana: "イナビ'カリ、スナ'ワチ/エエエンナ'リ",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-2/quotes/hsr-yomi.mp3': {
    text: '涙雨 降りて溢るる 渡り川',
    reading: 'なみだあめ ふりて あふるる わたりがわ',
    kana: "ナミダア'メ、フ'リテ/アフルル'、ワタリ'ガワ",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-2/quotes/quote-92c0994028.mp3': {
    text: '何だってかまわない。',
    reading: 'なんだって かまわない。',
    kana: "ナ'ンダッテ/カマワ'ナイ",
    reason: '局部指定讀音，保留其他詞的文字解析',
    reference: 'voicevox',
  },
  'audio/stage-2/quotes/quote-d3b5904f92.mp3': {
    text: '時よ止まれ!',
    reading: 'ときよ とまれ!',
    kana: "トキ'ヨ/トマレ'",
    reason: '局部指定時的とき讀音，採用 Kanjium 的時（とき）2型',
    reference: 'kanjium',
  },
  'audio/stage-0/day2/vocab-omiyage.mp3': {
    text: 'お土産',
    reading: 'おみやげ',
    kana: "オミヤゲ'",
    reason: '獨立單字採用 Kanjium 收錄的第一個重音型',
    reference: 'kanjium',
  },
  'audio/stage-0/day3/vocab-fd1e72e419.mp3': {
    text: '郵便局',
    reading: 'ゆうびんきょく',
    kana: "ユウビ'ンキョク",
    reason: '獨立單字採用 Kanjium 收錄的第一個重音型',
    reference: 'kanjium',
  },
  'audio/stage-0/day4/vocab-1a16339dd3.mp3': {
    text: '何時',
    reading: 'なんじ',
    kana: "ナ'ンジ",
    reason: '獨立單字採用 Kanjium 收錄的第一個重音型',
    reference: 'kanjium',
  },
  'audio/stage-0/day5/vocab-aaa56f9597.mp3': {
    text: '何日',
    reading: 'なんにち',
    kana: "ナ'ンニチ",
    reason: '獨立單字採用 Kanjium 收錄的第一個重音型',
    reference: 'kanjium',
  },
  'audio/stage-0/day5/vocab-573820ee1c.mp3': {
    text: '誕生日',
    reading: 'たんじょうび',
    kana: "タンジョ'オビ",
    reason: '獨立單字採用 Kanjium 收錄的第一個重音型',
    reference: 'kanjium',
  },
  'audio/stage-0/day6/vocab-4d58fdaf3f.mp3': {
    text: '昼ご飯',
    reading: 'ひるごはん',
    kana: "ヒルゴ'ハン",
    reason: '獨立單字採用 Kanjium 收錄的第一個重音型',
    reference: 'kanjium',
  },
  'audio/stage-0/day6/vocab-62e36a99d6.mp3': {
    text: '晩ご飯',
    reading: 'ばんごはん',
    kana: "バンゴ'ハン",
    reason: '獨立單字採用 Kanjium 收錄的第一個重音型',
    reference: 'kanjium',
  },
  'audio/stage-0/day7/vocab-9eab124e0d.mp3': {
    text: 'お菓子',
    reading: 'おかし',
    kana: "オカ'シ",
    reason: '獨立單字採用 Kanjium 收錄的第一個重音型',
    reference: 'kanjium',
  },
  'audio/stage-0/day11/vocab-6311c0303f.mp3': {
    text: '毎日',
    reading: 'まいにち',
    kana: "マ'イニチ",
    reason: '獨立單字採用 Kanjium 收錄的第一個重音型',
    reference: 'kanjium',
  },
  'audio/stage-0/day13/vocab-3ac7d9350c.mp3': {
    text: '映画館',
    reading: 'えいがかん',
    kana: "エエガ'カン",
    reason: '獨立單字採用 Kanjium 收錄的第一個重音型',
    reference: 'kanjium',
  },
  'audio/stage-0/day16/vocab-2f8425da21.mp3': {
    text: 'お風呂',
    reading: 'おふろ',
    kana: "オフ'ロ",
    reason: '獨立單字採用 Kanjium 收錄的第一個重音型',
    reference: 'kanjium',
  },
  'audio/stage-0/day17/vocab-56e6b20768.mp3': {
    text: 'お大事に',
    reading: 'おだいじに',
    kana: "オダイジニ'",
    reason: '獨立單字採用 Kanjium 收錄的第一個重音型',
    reference: 'kanjium',
  },
  'audio/stage-0/day23/vocab-1eac199c6c.mp3': {
    text: 'お弁当',
    reading: 'おべんとう',
    kana: "オベントオ'",
    reason: '獨立單字採用 Kanjium 收錄的第一個重音型',
    reference: 'kanjium',
  },
  'audio/stage-0/day23/vocab-cf85435cb7.mp3': {
    text: '昼御飯',
    reading: 'ひるごはん',
    kana: "ヒルゴ'ハン",
    reason: '獨立單字採用 Kanjium 收錄的第一個重音型',
    reference: 'kanjium',
  },
  'audio/stage-0/day23/vocab-1d874b8ece.mp3': {
    text: '晩御飯',
    reading: 'ばんごはん',
    kana: "バンゴ'ハン",
    reason: '獨立單字採用 Kanjium 收錄的第一個重音型',
    reference: 'kanjium',
  },
};
