/**
 * @typedef {{ jp: string, reading: string, zh: string, voice: string, audio: string }} Line
 * @typedef {{ pattern: string, note: string, examples: Line[], jlpt?: string[] }} GrammarPoint
 * @typedef {{ word: string, reading: string, zh: string, voice: string, audio: string }} VocabItem
 * @typedef {Line & { source: string, note: string }} Quote
 * @typedef {{ q: string, a: string }} PracticeItem
 * @typedef {{
 *   id: string,
 *   title: string,
 *   audioReady?: boolean,
 *   vocab: VocabItem[],
 *   grammar: GrammarPoint[],
 *   dialogue: Line[],
 *   quotes?: Quote[],
 *   practice: PracticeItem[],
 * }} Lesson
 * @typedef {{ id: string, title: string, lessons: Lesson[] }} Stage
 */

// 不含開頭斜線：由畫面端接上 Vite 的 BASE_URL，才能在 GitHub Pages 子路徑下正確解析。
const AUDIO_BASE = 'audio/stage-0/day1';

/** @type {Lesson} */
const day1 = {
  id: 'stage0-day1',
  title: '第 1 天：五十音自我檢查 + です／は／も',
  vocab: [
    { word: '私', reading: 'わたし', zh: '我', voice: 'zundamon', audio: `${AUDIO_BASE}/vocab-watashi.mp3` },
    { word: 'あなた', reading: 'あなた', zh: '你', voice: 'tsumugi', audio: `${AUDIO_BASE}/vocab-anata.mp3` },
    { word: '〜さん', reading: '〜さん', zh: '～先生／小姐（敬稱）', voice: 'hau', audio: `${AUDIO_BASE}/vocab-san.mp3` },
    { word: '学生', reading: 'がくせい', zh: '學生', voice: 'sayo', audio: `${AUDIO_BASE}/vocab-gakusei.mp3` },
    { word: '先生', reading: 'せんせい', zh: '老師', voice: 'miko', audio: `${AUDIO_BASE}/vocab-sensei.mp3` },
    { word: '会社員', reading: 'かいしゃいん', zh: '公司職員', voice: 'nana', audio: `${AUDIO_BASE}/vocab-kaishain.mp3` },
    { word: '何人', reading: 'なにじん', zh: '哪國人', voice: 'neko-vy', audio: `${AUDIO_BASE}/vocab-nanijin.mp3` },
    { word: '名前', reading: 'なまえ', zh: '名字', voice: 'chuugoku-usagi', audio: `${AUDIO_BASE}/vocab-namae.mp3` },
    { word: '国', reading: 'くに', zh: '國家', voice: 'zunko', audio: `${AUDIO_BASE}/vocab-kuni.mp3` },
  ],
  grammar: [
    {
      pattern: 'A は B です',
      jlpt: ['wa', 'desu'],
      note: 'A 是 B。です 是禮貌的斷定語氣，句尾語調平穩下降。',
      examples: [
        { jp: '私は学生です。', reading: 'わたしは がくせいです。', zh: '我是學生。', voice: 'zundamon', audio: `${AUDIO_BASE}/gram-1-1.mp3` },
        { jp: '田中さんは先生です。', reading: 'たなかさんは せんせいです。', zh: '田中先生是老師。', voice: 'zundamon', audio: `${AUDIO_BASE}/gram-1-2.mp3` },
      ],
    },
    {
      pattern: 'A は B ですか',
      jlpt: ['ka-question'],
      note: '疑問句，句尾加か、語調上揚，不用加「？」也成立。',
      examples: [
        { jp: 'あなたは会社員ですか。', reading: 'あなたは かいしゃいんですか。', zh: '你是公司職員嗎？', voice: 'zundamon', audio: `${AUDIO_BASE}/gram-2-1.mp3` },
        { jp: '田中さんは先生ですか。', reading: 'たなかさんは せんせいですか。', zh: '田中先生是老師嗎？', voice: 'zundamon', audio: `${AUDIO_BASE}/gram-2-2.mp3` },
      ],
    },
    {
      pattern: 'A は B では ありません',
      jlpt: ['de-wa-arimasen-ja-nai'],
      note: '否定句。口語常說成「じゃ ありません」，兩者意思一樣。',
      examples: [
        { jp: '私は先生ではありません。', reading: 'わたしは せんせいでは ありません。', zh: '我不是老師。', voice: 'zundamon', audio: `${AUDIO_BASE}/gram-3-1.mp3` },
        { jp: 'あなたは学生ではありません。', reading: 'あなたは がくせいでは ありません。', zh: '你不是學生。', voice: 'zundamon', audio: `${AUDIO_BASE}/gram-3-2.mp3` },
      ],
    },
    {
      pattern: 'A も B です',
      jlpt: ['mo'],
      note: '「也」的意思，替換掉は，提示前面已經講過同類的事。',
      examples: [
        { jp: '田中さんも学生です。', reading: 'たなかさんも がくせいです。', zh: '田中先生也是學生。', voice: 'zundamon', audio: `${AUDIO_BASE}/gram-4-1.mp3` },
        { jp: '私も会社員です。', reading: 'わたしも かいしゃいんです。', zh: '我也是公司職員。', voice: 'zundamon', audio: `${AUDIO_BASE}/gram-4-2.mp3` },
      ],
    },
  ],
  dialogue: [
    { jp: 'はじめまして。私ははうです。', reading: 'はじめまして。わたしは はうです。', zh: '初次見面，我是「はう」。', voice: 'hau', audio: `${AUDIO_BASE}/dlg-1.mp3` },
    { jp: 'はじめまして。私はミコです。', reading: 'はじめまして。わたしは ミコです。', zh: '初次見面，我是「ミコ」。', voice: 'miko', audio: `${AUDIO_BASE}/dlg-2.mp3` },
    { jp: 'ミコさんは学生ですか。', reading: 'ミコさんは がくせいですか。', zh: 'ミコ小姐是學生嗎？', voice: 'hau', audio: `${AUDIO_BASE}/dlg-3.mp3` },
    { jp: 'はい、学生です。はうさんも学生ですか。', reading: 'はい、がくせいです。はうさんも がくせいですか。', zh: '是的，是學生。はう小姐也是學生嗎？', voice: 'miko', audio: `${AUDIO_BASE}/dlg-4.mp3` },
    { jp: 'はい、私も学生です。どうぞよろしく。', reading: 'はい、わたしも がくせいです。どうぞ よろしく。', zh: '是的，我也是學生。請多指教。', voice: 'hau', audio: `${AUDIO_BASE}/dlg-5.mp3` },
    { jp: 'どうぞよろしく。', reading: 'どうぞ よろしく。', zh: '請多指教。', voice: 'miko', audio: `${AUDIO_BASE}/dlg-6.mp3` },
  ],
  practice: [
    { q: '「私は学生です。」を否定文にしてください。', a: '私は学生ではありません。' },
    { q: '填入助詞：田中さん___先生です。', a: 'は' },
    { q: '填入助詞：私は学生です。あなた___学生です。（表示「也」）', a: 'も' },
    { q: '「你是公司職員嗎？」用日文怎麼說？', a: 'あなたは会社員ですか。' },
    { q: '對話中，ミコ是學生嗎？她怎麼回答的？', a: '是學生。她說「はい、学生です。」' },
  ],
};

// audioReady: false 表示文字內容已完成、音檔尚未合成（合成需在有 VOICEVOX 與 ffmpeg 的機器上跑，
// 見 scripts/synthesize.mjs）。音檔產生並放進 public/ 之後，把這個旗標移除或改成 true。
// 旗標為 false 時畫面不顯示播放器，聽寫與跟讀也不會出現這些句子。
const SPOKEN_AUDIO = 'audio/stage-2/spoken';

/** @type {Lesson} */
const spoken = {
  id: 'stage2-spoken',
  title: '口語轉換表：教科書日文 → 動畫口語',
  audioReady: false,
  vocab: [],
  grammar: [
    {
      pattern: 'ている → てる',
      note: '口語把「い」省略。「ていない」變「てない」。動畫裡幾乎都是縮約形，只有正式場合才聽到完整的「ている」。',
      examples: [
        { jp: '雨が降っています。', reading: 'あめが ふって います。', zh: '教科書：正在下雨。', voice: 'sayo', audio: `${SPOKEN_AUDIO}/teru-1.mp3` },
        { jp: '雨が降ってる。', reading: 'あめが ふってる。', zh: '口語：正在下雨。', voice: 'tsumugi', audio: `${SPOKEN_AUDIO}/teru-2.mp3` },
      ],
    },
    {
      pattern: 'てしまう → ちゃう（でしまう → じゃう）',
      note: '表示「做完了」或「不小心、可惜」。口語說「ちゃう」；前面是「ん」音便時變「じゃう」（死んでしまう → 死んじゃう）。過去式「ちゃった」出現頻率非常高。',
      examples: [
        { jp: '宿題を忘れてしまいました。', reading: 'しゅくだいを わすれて しまいました。', zh: '教科書：我把作業忘了。', voice: 'sayo', audio: `${SPOKEN_AUDIO}/chau-1.mp3` },
        { jp: '宿題、忘れちゃった。', reading: 'しゅくだい、わすれちゃった。', zh: '口語：糟了，我把作業忘了。', voice: 'tsumugi', audio: `${SPOKEN_AUDIO}/chau-2.mp3` },
      ],
    },
    {
      pattern: 'ておく → とく（でおく → どく）',
      note: '表示「事先做好」。口語縮成「とく」，語氣輕鬆。',
      examples: [
        { jp: '先に買っておきます。', reading: 'さきに かって おきます。', zh: '教科書：我先買好。', voice: 'sayo', audio: `${SPOKEN_AUDIO}/toku-1.mp3` },
        { jp: '先に買っとく。', reading: 'さきに かっとく。', zh: '口語：我先買起來。', voice: 'tsumugi', audio: `${SPOKEN_AUDIO}/toku-2.mp3` },
      ],
    },
    {
      pattern: 'ては → ちゃ（では → じゃ）',
      note: '「〜てはいけない／ダメ」的口語是「〜ちゃいけない／ダメ」，表示禁止。動畫名句「逃げちゃダメだ」就是這個縮約。',
      examples: [
        { jp: 'ここで遊んではいけません。', reading: 'ここで あそんでは いけません。', zh: '教科書：不可以在這裡玩。', voice: 'sayo', audio: `${SPOKEN_AUDIO}/cha-1.mp3` },
        { jp: 'ここで遊んじゃダメ。', reading: 'ここで あそんじゃ ダメ。', zh: '口語：不可以在這裡玩。', voice: 'tsumugi', audio: `${SPOKEN_AUDIO}/cha-2.mp3` },
      ],
    },
    {
      pattern: 'なければ → なきゃ',
      note: '「〜なければならない」是「非…不可」。口語縮成「なきゃ」，後面的「ならない／いけない」常整段省略，單獨一句「行かなきゃ」就成立。',
      examples: [
        { jp: '早く行かなければなりません。', reading: 'はやく いかなければ なりません。', zh: '教科書：我必須快點去。', voice: 'sayo', audio: `${SPOKEN_AUDIO}/nakya-1.mp3` },
        { jp: '早く行かなきゃ。', reading: 'はやく いかなきゃ。', zh: '口語：得快點去才行。', voice: 'tsumugi', audio: `${SPOKEN_AUDIO}/nakya-2.mp3` },
      ],
    },
    {
      pattern: 'のだ／のです → んだ／んです',
      note: '說明原因、狀況或帶出心情的語氣（「其實是這樣啦」）。口語的「の」變成「ん」。疑問句更常直接用「の？」結尾。',
      examples: [
        { jp: '実は、行きたくないのです。', reading: 'じつは、いきたくないのです。', zh: '教科書：其實我不想去。', voice: 'sayo', audio: `${SPOKEN_AUDIO}/nda-1.mp3` },
        { jp: '実は、行きたくないんだ。', reading: 'じつは、いきたくないんだ。', zh: '口語：其實我不想去啦。', voice: 'tsumugi', audio: `${SPOKEN_AUDIO}/nda-2.mp3` },
      ],
    },
    {
      pattern: 'と言う → って',
      note: '轉述別人的話時，口語常把「と」換成「って」，連「言う」都可以省略，帶有「聽說」的傳聞語氣。',
      examples: [
        { jp: '田中さんは来ないと言いました。', reading: 'たなかさんは こないと いいました。', zh: '教科書：田中先生說他不來。', voice: 'sayo', audio: `${SPOKEN_AUDIO}/tte-1.mp3` },
        { jp: '田中さん、来ないって。', reading: 'たなかさん、こないって。', zh: '口語：田中說他不來喔。', voice: 'tsumugi', audio: `${SPOKEN_AUDIO}/tte-2.mp3` },
      ],
    },
    {
      pattern: 'ら抜き言葉（食べられる → 食べれる）',
      note: '一段動詞（食べる、見る、起きる）的可能形，口語常把「ら」拿掉。聽得懂就好，考試與正式文章仍用完整的「られる」。五段動詞（行く → 行ける）本來就沒有「ら」。',
      examples: [
        { jp: '朝ごはんが食べられません。', reading: 'あさごはんが たべられません。', zh: '教科書：我吃不下早餐。', voice: 'sayo', audio: `${SPOKEN_AUDIO}/rasnuki-1.mp3` },
        { jp: '朝ごはん、食べれない。', reading: 'あさごはん、たべれない。', zh: '口語：早餐吃不下。', voice: 'tsumugi', audio: `${SPOKEN_AUDIO}/rasnuki-2.mp3` },
      ],
    },
    {
      pattern: '語尾：よ／ね／よね',
      note: '「よ」告訴對方對方可能不知道的事；「ね」尋求對方同意、共鳴；「よね」是「我覺得是這樣，對吧？」的確認。三個都沒有實際詞義，卻決定了整句的態度。',
      examples: [
        { jp: 'このラーメン、おいしいよ。', reading: 'この ラーメン、おいしいよ。', zh: '這碗拉麵很好吃喔（我告訴你）。', voice: 'tsumugi', audio: `${SPOKEN_AUDIO}/yone-1.mp3` },
        { jp: 'このラーメン、おいしいよね。', reading: 'この ラーメン、おいしいよね。', zh: '這碗拉麵很好吃，對吧？', voice: 'hau', audio: `${SPOKEN_AUDIO}/yone-2.mp3` },
      ],
    },
    {
      pattern: '語尾：ぞ／ぜ／わ／かしら（角色語氣）',
      note: '「ぞ」「ぜ」是男性化、帶力道的斷定，動畫裡常見於熱血角色；「わ」「かしら」是女性化或大小姐口吻的語氣。現實生活的自然對話中很少這樣說，學會聽懂即可，不要自己模仿。',
      examples: [
        { jp: 'そろそろ行くぞ。', reading: 'そろそろ いくぞ。', zh: '差不多該出發了！（男性、有力）', voice: 'nana', audio: `${SPOKEN_AUDIO}/kyara-1.mp3` },
        { jp: 'あの人、誰かしら。', reading: 'あの ひと、だれかしら。', zh: '那個人是誰呢？（女性、自言自語）', voice: 'miko', audio: `${SPOKEN_AUDIO}/kyara-2.mp3` },
      ],
    },
  ],
  dialogue: [],
  practice: [
    { q: '把「雨が降っています。」改成口語縮約形。', a: '雨が降ってる。' },
    { q: '把「宿題を忘れてしまった。」改成口語縮約形。', a: '宿題、忘れちゃった。' },
    { q: '把「行かなければならない。」改成口語縮約形。', a: '行かなきゃ。（或行かなきゃならない）' },
    { q: '把「ここで遊んではいけない。」改成口語縮約形。', a: 'ここで遊んじゃいけない。（或遊んじゃダメ）' },
    { q: '「食べられない」的ら抜き形式是什麼？', a: '食べれない' },
    { q: '想向對方確認「你也這樣覺得吧」，句尾用「よ」還是「ね」（或「よね」）？', a: 'ね（或よね）。「よ」是告知對方不知道的事。' },
  ],
};

const QUOTES_AUDIO = 'audio/stage-2/quotes';

// 每句只收單句短台詞，標明出處，解說為自己撰寫。音檔一律用 VOICEVOX 自製合成，不使用原配音。
// 台詞用字已用網路搜尋交叉確認（二手來源，非原作台本）；首批只是常見名句，之後依 Michael 想聽懂的作品增補。
/** @type {Lesson} */
const quotes = {
  id: 'stage2-quotes',
  title: '動畫與遊戲名句：短句與口語重點',
  audioReady: false,
  vocab: [],
  grammar: [],
  dialogue: [],
  quotes: [
    {
      jp: '諦めたらそこで試合終了ですよ。',
      reading: 'あきらめたら そこで しあい しゅうりょう ですよ。',
      zh: '一旦放棄，比賽就在那裡結束了。',
      voice: 'sayo',
      audio: `${QUOTES_AUDIO}/slamdunk.mp3`,
      source: 'SLAM DUNK（安西先生）',
      note: '「〜たら」是「一旦…就」；「そこで」指「就在那個時間點」；句尾「ですよ」是禮貌語加上「我告訴你」的提醒語氣。',
    },
    {
      jp: 'お前はもう死んでいる。',
      reading: 'おまえは もう しんで いる。',
      zh: '你已經死了。',
      voice: 'nana',
      audio: `${QUOTES_AUDIO}/hokuto.mp3`,
      source: '北斗の拳（ケンシロウ）',
      note: '「お前」是對同輩或晚輩的粗魯稱呼；「死んでいる」的「ている」表結果狀態（已經是死的狀態），不是「正在死」，口語會縮成「死んでる」。',
    },
    {
      jp: '真実はいつもひとつ！',
      reading: 'しんじつは いつも ひとつ！',
      zh: '真相永遠只有一個！',
      voice: 'tsumugi',
      audio: `${QUOTES_AUDIO}/conan.mp3`,
      source: '名探偵コナン（江戸川コナン）',
      note: '名詞句，省略了「です／だ」，短促有力。「は」提示主題，「いつも」是「總是」。這句以動畫版與劇場版的招牌決め台詞最為人所知。',
    },
    {
      jp: '逃げちゃダメだ。',
      reading: 'にげちゃ ダメだ。',
      zh: '不能逃避。',
      voice: 'neko-vy',
      audio: `${QUOTES_AUDIO}/eva.mp3`,
      source: '新世紀エヴァンゲリオン（碇シンジ）',
      note: '「逃げてはダメだ」的口語縮約（ては → ちゃ，見口語轉換表）。「ダメ」是「不行」。',
    },
    {
      jp: '月に代わっておしおきよ！',
      reading: 'つきに かわって おしおきよ！',
      zh: '代替月亮，懲罰你！',
      voice: 'miko',
      audio: `${QUOTES_AUDIO}/sailormoon.mp3`,
      source: '美少女戦士セーラームーン',
      note: '「〜に代わって」是「代替…」；「おしおき」原本是對小孩的責罰，帶點俏皮；句尾「よ」是告知語氣，這裡偏女性化。',
    },
    {
      jp: '海賊王におれはなる！',
      reading: 'かいぞくおうに おれは なる！',
      zh: '我要成為海賊王！',
      voice: 'zunko',
      audio: `${QUOTES_AUDIO}/onepiece.mp3`,
      source: 'ONE PIECE（モンキー・D・ルフィ）',
      note: '平常語序是「おれは海賊王になる」，把「海賊王に」提到句首是倒裝，用來強調目標。「おれ」是男性自稱；「なる」現在形在這裡表決心。',
    },
    {
      jp: '私、気になります！',
      reading: 'わたし、きに なります！',
      zh: '我很在意（好奇）！',
      voice: 'hau',
      audio: `${QUOTES_AUDIO}/hyouka.mp3`,
      source: '氷菓（千反田える）',
      note: '「気になる」是「放不下心、忍不住在意」，用「なる」表示是自然變成這樣，而非刻意。「私、」後面停頓並省略「は」，是口語習慣。',
    },
    {
      jp: '僕は新世界の神となる。',
      reading: 'ぼくは しんせかいの かみと なる。',
      zh: '我要成為新世界的神。',
      voice: 'chuugoku-usagi',
      audio: `${QUOTES_AUDIO}/deathnote.mp3`,
      source: 'DEATH NOTE（夜神月）',
      note: '「〜となる」和「〜になる」都是「成為」，「となる」較書面、莊重。「僕」比「おれ」溫和，和前面海賊王的例句可以對照自稱的語感。',
    },
    {
      jp: 'なんとかなれーッ！',
      reading: 'なんとか なれーッ！',
      zh: '一定要成功啊！（拼了！）',
      voice: 'neko-vy',
      audio: `${QUOTES_AUDIO}/chiikawa-nantoka.mp3`,
      source: 'ちいかわ（ハチワレ）',
      note: '「なんとかなる」（總會有辦法）的命令形「なれ」。這裡不是命令別人，而是替自己或事情打氣、祈求好結果。拉長的「ー」和小「ッ」表示用力喊出來的語氣。',
    },
    {
      jp: 'ヤダッ！',
      reading: 'ヤダッ！',
      zh: '不要！',
      voice: 'hau',
      audio: `${QUOTES_AUDIO}/chiikawa-yada.mp3`,
      source: 'ちいかわ（ちいかわ）',
      note: '「やだ」是「いやだ」的口語縮略，表示拒絕或嫌惡。小「ッ」讓語氣變得急促、斬釘截鐵。',
    },
    {
      jp: 'ポケモンゲットだぜ！',
      reading: 'ポケモン ゲットだぜ！',
      zh: '收服寶可夢囉！',
      voice: 'nana',
      audio: `${QUOTES_AUDIO}/pokemon-get.mp3`,
      source: 'ポケットモンスター（アニメ・サトシ）',
      note: '「ゲット」是英語 get 借來的外來語，「ゲットする」就是「得到、抓到」。句尾「だぜ」是「だ」加上男性化、帶勁的「ぜ」（見口語轉換表的「ぞ／ぜ」）。',
    },
    {
      jp: 'ピカチュウ、きみに決めた！',
      reading: 'ピカチュウ、きみに きめた！',
      zh: '皮卡丘，就決定是你了！',
      voice: 'tsumugi',
      audio: `${QUOTES_AUDIO}/pokemon-kimi.mp3`,
      source: 'ポケットモンスター（アニメ・サトシ）',
      note: '「AをBに決める」是在幾個選項裡選定 B，用「〜に決めた」表示「就決定是你了」。「決めた」的過去式在這裡是「決心已下」，不是過去發生的事。「きみ」是對同輩或夥伴的親暱稱呼。',
    },
    {
      jp: 'やなかんじー！',
      reading: 'やな かんじー！',
      zh: '真是討厭的感覺～！',
      voice: 'zundamon',
      audio: `${QUOTES_AUDIO}/pokemon-rocket.mp3`,
      source: 'ポケットモンスター（アニメ・ロケット団）',
      note: '「やな」是「いやな」的口語縮略（頭一個「い」脫落），「かんじ」是「感じ」，整句就是「いやな感じだ」。拖長尾音是敗北時的招牌耍寶語氣。',
    },
    {
      jp: 'えへってなんだよ！',
      reading: 'えへって なんだよ！',
      zh: '什麼「嘿嘿」啊！',
      voice: 'miko',
      audio: `${QUOTES_AUDIO}/genshin-paimon.mp3`,
      source: '原神（パイモン）',
      note: '「〜ってなんだよ」是「〜とは何だ」的口語吐槽：「って」引用剛聽到的詞，句尾「なんだよ」帶出不滿或吐槽。ウェンティ用「えへ」矇混過關之後，パイモン用這句回嘴，成為知名的網路梗。',
    },
    {
      jp: '稲光、すなわち永遠なり。',
      reading: 'いなびかり、すなわち えいえん なり。',
      zh: '閃電，即是永恆。',
      voice: 'chuugoku-usagi',
      audio: `${QUOTES_AUDIO}/genshin-raiden.mp3`,
      source: '原神（雷電将軍）',
      note: '「すなわち」是「換句話說、即是」；句尾「なり」是文言（古文）的斷定，相當於現代的「である」，聽起來莊嚴、像宣言。屬於角色語氣，日常對話不會這樣說。',
    },
    {
      jp: 'それがオレの忍道だ！',
      reading: 'それが オレの にんどうだ！',
      zh: '這就是我的忍道！',
      voice: 'nana',
      audio: `${QUOTES_AUDIO}/naruto-nindo.mp3`,
      source: 'NARUTO -ナルト-（うずまきナルト）',
      note: '「忍道」是「身為忍者的生存之道」，也就是自己信奉、絕不違背的原則。「それが」的「が」強調「正是這個」。ナルト的口癖是句尾加「〜だってばよ」，屬於他個人的角色語氣。',
    },
    {
      jp: '勇者ヒンメルならそうした。',
      reading: 'ゆうしゃ ヒンメルなら そうした。',
      zh: '換作勇者辛美爾，就會這麼做。',
      voice: 'sayo',
      audio: `${QUOTES_AUDIO}/frieren-himmel.mp3`,
      source: '葬送のフリーレン（作中反覆出現的一句話）',
      note: '「Aなら」是「如果是 A 的話、換作是 A」；「そうした」用過去式，是回想「當年他就是這麼做的」，把它當作自己現在行動的依據。',
    },
    {
      jp: '魔法は探し求めている時が一番楽しいんだよ。',
      reading: 'まほうは さがしもとめて いる ときが いちばん たのしいんだよ。',
      zh: '魔法啊，在尋找的時候最有趣了。',
      voice: 'chuugoku-usagi',
      audio: `${QUOTES_AUDIO}/frieren-magic.mp3`,
      source: '葬送のフリーレン（フリーレン）',
      note: '「〜ている時が一番〜」是「在…的時候最…」。句尾「んだよ」是「のだ」的口語（見口語轉換表），用來向對方解釋「事情是這樣的喔」。',
    },
    {
      jp: '涙雨 降りて溢るる 渡り川',
      reading: 'なみだあめ ふりて あふるる わたりがわ',
      zh: '淚雨落下，滿溢了渡川。',
      voice: 'sayo',
      audio: `${QUOTES_AUDIO}/hsr-yomi.mp3`,
      source: '崩壊：スターレイル（黄泉）',
      note: '五、七、五音節的和歌風一句，用的是文言（古文）：「溢るる」是「溢れる」的文語連體形，「渡り川」是「要渡過的河」，也是三途川的別名。現代日語不會這樣說，屬於角色的詩意台詞。',
    },
    {
      jp: '殴ったね？',
      reading: 'なぐったね？',
      zh: '你居然動手打我？',
      voice: 'miko',
      audio: `${QUOTES_AUDIO}/hsr-march7.mp3`,
      source: '崩壊：スターレイル（三月なのか）',
      note: '「殴る」的過去式「殴った」加終助詞「ね」，用來確認事實並帶著驚訝或指責的語氣：「你打我喔？」。這是她天賦反擊時的戰鬥語音。',
    },
    {
      jp: 'クルクルー！',
      reading: 'クルクルー！',
      zh: '（轉圈時的掛聲，沒有字面意思）',
      voice: 'tsumugi',
      audio: `${QUOTES_AUDIO}/hsr-herta.mp3`,
      source: '崩壊：スターレイル（ヘルタ）',
      note: '沒有字面意義的掛聲，是ヘルタ發動追加攻擊時的語音，也成為網路梗（據報導日文語音限定）。學它是為了聽出拉長音「ー」和節奏，不是學詞彙。',
    },
    {
      jp: '心を燃やせ！',
      reading: 'こころを もやせ！',
      zh: '燃燒你的心！',
      voice: 'nana',
      audio: `${QUOTES_AUDIO}/kimetsu-kokoro.mp3`,
      source: '鬼滅の刃（煉獄杏寿郎）',
      note: '「燃やす」（把…點燃）的命令形「燃やせ」。「燃える」是自動詞（自己燃燒），「燃やす」是他動詞，這裡表示要「主動點燃內心的鬥志」。命令形語氣強硬，多用在激勵或上對下。',
    },
    {
      jp: 'うまい！',
      reading: 'うまい！',
      zh: '好吃！',
      voice: 'zunko',
      audio: `${QUOTES_AUDIO}/kimetsu-umai.mp3`,
      source: '鬼滅の刃（煉獄杏寿郎）',
      note: '「うまい」是「おいしい」較男性化的口語說法（漢字寫「旨い」），也能表示「厲害、高明」。他邊吃便當邊連喊三次，是直率性格的代表。',
    },
    {
      jp: '胸を張って生きろ。',
      reading: 'むねを はって いきろ。',
      zh: '要挺起胸膛活下去。',
      voice: 'sayo',
      audio: `${QUOTES_AUDIO}/kimetsu-mune.mp3`,
      source: '鬼滅の刃（煉獄杏寿郎）',
      note: '「胸を張る」是慣用語，字面是「挺起胸膛」，引申為「抬頭挺胸、問心無愧」。「張って」是て形，後面接「生きろ」（生きる的命令形）。',
    },
    {
      jp: 'だが断る！',
      reading: 'だが ことわる！',
      zh: '可是我拒絕！',
      voice: 'nana',
      audio: `${QUOTES_AUDIO}/jojo-rohan.mp3`,
      source: 'ジョジョの奇妙な冒険（岸辺露伴）',
      note: '「だが」是「可是、但是」，比「でも」更書面、更強硬；「断る」是「拒絕」，用原形直接當句子，語氣不留餘地，聽起來像宣言。',
    },
    {
      jp: 'やれやれだぜ。',
      reading: 'やれやれだぜ。',
      zh: '唉，真是的。',
      voice: 'sayo',
      audio: `${QUOTES_AUDIO}/jojo-jotaro.mp3`,
      source: 'ジョジョの奇妙な冒険（空条承太郎）',
      note: '「やれやれ」是無奈或嫌麻煩時的嘆息，相當於「唉，真是的」。句尾「だぜ」是男性化、帶勁的語氣（見口語轉換表的「ぞ／ぜ」）。',
    },
    {
      jp: '無駄無駄無駄無駄！',
      reading: 'むだ むだ むだ むだ！',
      zh: '沒用沒用沒用沒用！',
      voice: 'nana',
      audio: `${QUOTES_AUDIO}/jojo-dio.mp3`,
      source: 'ジョジョの奇妙な冒険（DIO）',
      note: '「無駄」是「白費、沒用」。原作與動畫裡這句會連續重複很多次，這裡只收縮短版；聽的重點是節奏和氣勢，不是詞彙。',
    },
    {
      jp: 'あたしのココロ、アンロック！',
      reading: 'あたしの ココロ、アンロック！',
      zh: '我的心，解鎖！',
      voice: 'tsumugi',
      audio: `${QUOTES_AUDIO}/shugochara-amu.mp3`,
      source: 'しゅごキャラ！（日奈森あむ）',
      note: '「アンロック」是英語 unlock（解鎖），「ココロ」刻意用片假名，強調的是「心」這個概念。「あたし」是女性口語的自稱，比「わたし」更隨性。',
    },
    {
      jp: 'お前がいなくなるとダメになるのは俺のほうだ。',
      reading: 'おまえが いなくなると ダメになるのは おれの ほうだ。',
      zh: '你要是不在了，會撐不下去的是我才對。',
      voice: 'neko-vy',
      audio: `${QUOTES_AUDIO}/kodocha-hayama.mp3`,
      source: 'こどものおもちゃ（羽山秋人）',
      note: '「〜のは俺のほうだ」是分裂強調句：把想強調的「是我這一邊」放在最後。「ダメになる」是「變得不行、垮掉」，「〜と」表示「一旦…就」，「お前」「俺」是男性口語的第二、第一人稱。',
    },
    {
      jp: '思うだけでいーんだ。見返りはいらない。',
      reading: 'おもうだけで いーんだ。みかえりは いらない。',
      zh: '只要在心裡想著就好，我不求回報。',
      voice: 'hau',
      audio: `${QUOTES_AUDIO}/kodocha-sana.mp3`,
      source: 'こどものおもちゃ（倉田紗南）',
      note: '「いーんだ」是「いいんだ」拉長音的口語，「〜んだ」是「のだ」，帶著說明、堅定的語氣。「見返り」是「回報」，「いらない」是「不需要」。',
    },
    {
      jp: 'おすわり！',
      reading: 'おすわり！',
      zh: '坐下！',
      voice: 'miko',
      audio: `${QUOTES_AUDIO}/inuyasha-osuwari.mp3`,
      source: '犬夜叉（日暮かごめ）',
      note: '「おすわり」是對狗說的「坐下」，由「座る」的名詞形加上美化語「お」構成。在作品裡，かごめ用這個口令讓被念珠束縛的犬夜叉倒地。',
    },
    {
      jp: 'ただの人間には興味ありません。',
      reading: 'ただの にんげんには きょうみ ありません。',
      zh: '普通的人類我沒有興趣。',
      voice: 'tsumugi',
      audio: `${QUOTES_AUDIO}/haruhi-jikoshoukai.mp3`,
      source: '涼宮ハルヒの憂鬱（涼宮ハルヒ）',
      note: '「ただの〜」是「僅僅是、普通的」，「〜には興味ありません」是禮貌的否定「對…沒有興趣」，語氣禮貌卻很傲慢。這是第一集入學自我介紹的開場句，後面接著點名想找的宇宙人、未來人等等。',
    },
    {
      jp: 'やれやれ。',
      reading: 'やれやれ。',
      zh: '唉，真是的。',
      voice: 'sayo',
      audio: `${QUOTES_AUDIO}/haruhi-kyon.mp3`,
      source: '涼宮ハルヒの憂鬱（キョン）',
      note: '「やれやれ」是無奈、嫌麻煩時的嘆息，是キョン的口癖，他常在旁白裡用。前面承太郎的「やれやれだぜ」是同一個詞加上男性化的語尾。',
    },
    {
      jp: '「あいしてる」を知りたいのです。',
      reading: '「あいしてる」を しりたいのです。',
      zh: '我想知道什麼是「愛」。',
      voice: 'hau',
      audio: `${QUOTES_AUDIO}/violet-know.mp3`,
      source: 'ヴァイオレット・エヴァーガーデン（ヴァイオレット）',
      note: '「知りたい」是「想知道」，「のです」是「のだ」的禮貌形（見口語轉換表），她講話一律用丁寧語，用「のです」說明自己的心意與狀況。',
    },
    {
      jp: '心から、愛してる。',
      reading: 'こころから、あいしてる。',
      zh: '我發自內心愛你。',
      voice: 'zunko',
      audio: `${QUOTES_AUDIO}/violet-gilbert.mp3`,
      source: 'ヴァイオレット・エヴァーガーデン（ギルベルト）',
      note: '「愛してる」是「愛している」省略「い」的口語（見口語轉換表的「ている → てる」），是直接的告白。「心から」是「發自內心」，中間的停頓是台詞的節奏。',
    },
    {
      jp: '女のコなんだから気をつけなきゃ。',
      reading: 'おんなのコなんだから きを つけなきゃ。',
      zh: '你是女孩子，要小心一點才行。',
      voice: 'neko-vy',
      audio: `${QUOTES_AUDIO}/hanako-kiwotsukete.mp3`,
      source: '地縛少年花子くん（花子くん）',
      note: '「なんだから」表示理由（因為是女孩子）；「気をつけなきゃ」是「気をつけなければ（ならない）」的口語（見口語轉換表的「なければ → なきゃ」），後面的「ならない」整段省略。',
    },
    {
      jp: '好きな人に会いに来たの！',
      reading: 'すきな ひとに あいに きたの！',
      zh: '我是來見喜歡的人的！',
      voice: 'miko',
      audio: `${QUOTES_AUDIO}/hanako-nene.mp3`,
      source: '地縛少年花子くん（八尋寧々）',
      note: '「〜に会いに来る」是「來見…」，前面的「に」表示目的。句尾「の」是說明理由的口語（等於「んだ」），女性更常用，語氣理直氣壯。',
    },
    {
      jp: 'もし私を処刑する場合、毒殺にしていただけませんか。',
      reading: 'もし わたしを しょけいする ばあい、どくさつに して いただけませんか。',
      zh: '如果要處死我的話，可以請您用毒殺嗎？',
      voice: 'sayo',
      audio: `${QUOTES_AUDIO}/kusuriya-poison.mp3`,
      source: '薬屋のひとりごと（猫猫）',
      note: '「もし〜場合」是「如果…的情況下」；「〜にしていただけませんか」是很禮貌的請求「可以請您改成…嗎」。內容卻是請對方用毒殺處死自己，禮貌與內容的反差正是猫猫的個性。',
    },
    {
      jp: 'みんな、閉じこもった空気に毒されていく。',
      reading: 'みんな、とじこもった くうきに どくされて いく。',
      zh: '大家都會被封閉的空氣毒害。',
      voice: 'chuugoku-usagi',
      audio: `${QUOTES_AUDIO}/kusuriya-air.mp3`,
      source: '薬屋のひとりごと（猫猫）',
      note: '「毒される」是「毒す」的被動形，字面是「被毒害」，引申為「被不好的氛圍或影響侵蝕」，也呼應作品的「毒」主題。「閉じこもる」是「關在裡面、封閉」，「〜ていく」表示逐漸變化下去。',
    },
    {
      jp: '俺は絶えずレベルアップしている。',
      reading: 'おれは たえず レベルアップして いる。',
      zh: '我一直在不斷升級。',
      voice: 'nana',
      audio: `${QUOTES_AUDIO}/sololeveling-levelup.mp3`,
      source: '俺だけレベルアップな件（水篠旬）',
      note: '「絶えず」是「不間斷地」，比「ずっと」書面；「〜ている」表示持續進行，口語會縮成「レベルアップしてる」。「レベルアップ」是外來語，可以直接接「する」變成動詞。',
    },
    {
      jp: '弱いからなめられるんだ。',
      reading: 'よわいから なめられるんだ。',
      zh: '就是因為弱，才會被人瞧不起啊。',
      voice: 'neko-vy',
      audio: `${QUOTES_AUDIO}/sololeveling-weak.mp3`,
      source: '俺だけレベルアップな件（水篠旬）',
      note: '「弱いから」是理由；「なめられる」是「なめる」（瞧不起）的被動形；句尾「んだ」（のだ）帶說明、自省的語氣，整句是「就是因為弱才會這樣」。',
    },
    {
      jp: '心臓を捧げよ！',
      reading: 'しんぞうを ささげよ！',
      zh: '獻出你的心臟！',
      voice: 'nana',
      audio: `${QUOTES_AUDIO}/aot-erwin.mp3`,
      source: '進撃の巨人（エルヴィン・スミス）',
      note: '「捧げる」的命令形「捧げよ」是較古風、莊重的命令形，比口語的「捧げろ」更像號令。在作品裡是調查兵團的敬禮口令，表示願意獻出性命。',
    },
    {
      jp: '駆逐してやる！',
      reading: 'くちく してやる！',
      zh: '我要把你們驅逐殆盡！',
      voice: 'zundamon',
      audio: `${QUOTES_AUDIO}/aot-eren.mp3`,
      source: '進撃の巨人（エレン・イェーガー）',
      note: '「〜してやる」是「我非…不可」的決心或威嚇，「やる」在這裡是「給對方好看」的意思，語氣粗魯。「駆逐」是「驅逐、消滅」。原句後面還接「この世から…一匹…残らず」，這裡只收前半。',
    },
    {
      jp: '大丈夫、僕最強だから。',
      reading: 'だいじょうぶ、ぼく さいきょうだから。',
      zh: '沒問題，因為我是最強的。',
      voice: 'sayo',
      audio: `${QUOTES_AUDIO}/jjk-gojo.mp3`,
      source: '呪術廻戦（五条悟）',
      note: '句尾的「〜だから」是「因為…（所以請放心）」的省略說法，把理由當作結論。「僕最強」省略了主題助詞「は」，是很口語的說法。',
    },
    {
      jp: 'わくわく！',
      reading: 'わくわく！',
      zh: '好期待！',
      voice: 'hau',
      audio: `${QUOTES_AUDIO}/spyfamily-anya.mp3`,
      source: 'SPY×FAMILY（アーニャ）',
      note: '「わくわく」是擬態語，表示期待到心跳加速。アーニャ是小孩，說話常用簡單的擬態語，還有不標準的日語（例如「あざざます」），這是角色設定，不要當成標準日語模仿。',
    },
    {
      jp: '私が来た！',
      reading: 'わたしが きた！',
      zh: '因為有我在這裡！',
      voice: 'tsumugi',
      audio: `${QUOTES_AUDIO}/mha-allmight.mp3`,
      source: '僕のヒーローアカデミア（オールマイト）',
      note: '完整的句子是「もう大丈夫！何故って？私が来た！」，「何故って」是自問自答，引出理由。「私が来た」的「が」強調「正是我來了」。',
    },
    {
      jp: '君が救けを求める顔してた',
      reading: 'きみが たすけを もとめる かお してた',
      zh: '因為你露出了求救的表情。',
      voice: 'neko-vy',
      audio: `${QUOTES_AUDIO}/mha-deku.mp3`,
      source: '僕のヒーローアカデミア（緑谷出久）',
      note: '「救け」是「助け」的另一種寫法，念作「たすけ」。「顔してた」是「顔をしていた」省略「を」的口語，「ている → てる」再變成過去式（見口語轉換表）。',
    },
    {
      jp: '坊やだからさ',
      reading: 'ぼうやだからさ',
      zh: '因為他是個毛頭小子啊。',
      voice: 'sayo',
      audio: `${QUOTES_AUDIO}/gundam-bouya.mp3`,
      source: '機動戦士ガンダム（シャア・アズナブル）',
      note: '「坊や」是對小孩或年輕人的稱呼，帶點輕視；「だからさ」是「だから」加上口語終助詞「さ」，表示「理由就是這樣啊」。',
    },
    {
      jp: '認めたくないものだな',
      reading: 'みとめたく ないものだな',
      zh: '真是不願承認啊。',
      voice: 'chuugoku-usagi',
      audio: `${QUOTES_AUDIO}/gundam-mitometakunai.mp3`,
      source: '機動戦士ガンダム（シャア・アズナブル）',
      note: '「〜たくない」是「不想…」，「ものだな」是「真是…啊」的感嘆，帶著自嘲。原句後面還接「自分自身の若さゆえの過ちというものを」，這裡只收前半。',
    },
    {
      jp: 'オラ、ワクワクしてきたぞ！',
      reading: 'オラ、ワクワクして きたぞ！',
      zh: '我開始興奮起來啦！',
      voice: 'zunko',
      audio: `${QUOTES_AUDIO}/dragonball-wakuwaku.mp3`,
      source: 'ドラゴンボール（孫悟空）',
      note: '「オラ」是「おれ」的方言式說法，是悟空的自稱；「〜てきた」表示「開始變成…的狀態」；句尾「ぞ」是男性化的語尾（見口語轉換表）。',
    },
    {
      jp: 'オッス！オラ悟空！',
      reading: 'オッス！オラ ごくう！',
      zh: '嘿！我是悟空！',
      voice: 'tsumugi',
      audio: `${QUOTES_AUDIO}/dragonball-ossu.mp3`,
      source: 'ドラゴンボール（孫悟空）',
      note: '「オッス」是男生之間隨性打招呼的說法。這句招牌開場白據報導在原作漫畫裡沒有，是動畫次回預告的開頭才固定下來。',
    },
    {
      jp: '僕と契約して、魔法少女になってよ！',
      reading: 'ぼくと けいやくして、まほうしょうじょに なってよ！',
      zh: '和我簽約，成為魔法少女吧！',
      voice: 'miko',
      audio: `${QUOTES_AUDIO}/madoka-kyubey.mp3`,
      source: '魔法少女まどか☆マギカ（キュゥべえ）',
      note: '「〜になってよ」是「請你成為…吧」的請求，用「て形＋よ」比命令柔和，像在哄人。「契約する」是「簽訂契約」。這句話曾入選 2011 年的網路流行語。',
    },
    {
      jp: '嘘はとびきりの愛なんだよ。',
      reading: 'うそは とびきりの あいなんだよ。',
      zh: '謊言是最棒的愛啊。',
      voice: 'hau',
      audio: `${QUOTES_AUDIO}/oshinoko-ai.mp3`,
      source: '推しの子（星野アイ）',
      note: '「とびきり」是「格外、特別（好）」，有些網站寫成「とびっきり」。「愛なんだよ」的「なんだ」是「なのだ」，用來向對方說明「事情是這樣的喔」。',
    },
    {
      jp: '40秒で支度しな！',
      reading: 'よんじゅうびょうで したくしな！',
      zh: '給你四十秒準備！',
      voice: 'nana',
      audio: `${QUOTES_AUDIO}/laputa-dora.mp3`,
      source: '天空の城ラピュタ（ドーラ）',
      note: '「〜しな」是「〜しなさい」的口語縮略，帶著命令、催促的語氣，多見於長輩對晚輩。「支度」是「準備、打理」；「40秒で」的「で」表示所需的時間或期限。',
    },
    {
      jp: '見ろ！人がゴミのようだ！',
      reading: 'みろ！ひとが ゴミの ようだ！',
      zh: '看啊！人就像垃圾一樣！',
      voice: 'zundamon',
      audio: `${QUOTES_AUDIO}/laputa-muska.mp3`,
      source: '天空の城ラピュタ（ムスカ）',
      note: '「見ろ」是「見る」的命令形；「〜のようだ」是「像…一樣」的比喻，這裡是輕蔑的比喻。語氣傲慢誇張，是反派台詞的典型風格。',
    },
    {
      jp: 'しんでしまうとは なにごとだ！',
      reading: 'しんで しまうとは なにごとだ！',
      zh: '居然死掉了，成何體統！',
      voice: 'sayo',
      audio: `${QUOTES_AUDIO}/dq-king.mp3`,
      source: 'ドラゴンクエスト（王様・初代）',
      note: '「〜とは」表示驚訝或責備；「しんでしまう」是「死んでしまう」（てしまう，口語會縮成「死んじゃう」，見口語轉換表）。系列各作的結尾不同：初代是「なにごとだ」，其他作品有「なさけない」「ふがいない」等。遊戲文字全用平假名。',
    },
    {
      jp: 'イカ、よろしくー！',
      reading: 'イカ、よろしくー！',
      zh: '烏賊，多多指教～！',
      voice: 'miko',
      audio: `${QUOTES_AUDIO}/splatoon-shiokarazu.mp3`,
      source: 'スプラトゥーン（シオカラーズ）',
      note: '遊戲以烏賊（イカ）為主角，所以連打招呼都要加上「イカ」。「よろしく」是「よろしくお願いします」的省略說法，拖長的「ー」是唱歌般的語氣。',
    },
  ],
  practice: [
    { q: '「逃げちゃダメだ」還原成教科書形是什麼？', a: '逃げてはダメだ（逃げてはいけない）。' },
    { q: '「お前はもう死んでいる」的「死んでいる」是「正在死」還是「已經是死的狀態」？', a: '已經是死的狀態（結果狀態）。' },
    { q: '「海賊王におれはなる」的正常語序是？', a: 'おれは海賊王になる。' },
    { q: '「やなかんじ」的「やな」是哪個詞縮短來的？', a: '「いやな」（頭一個「い」脫落）。' },
    { q: '「ポケモンゲットだぜ」的句尾「ぜ」是男性化還是女性化的語氣？', a: '男性化、帶力道（見口語轉換表的「ぞ／ぜ」）。' },
    { q: '「えへってなんだよ」的「って」在這裡的作用是什麼？', a: '引用剛聽到的詞，相當於「〜という／〜とは」。' },
    { q: '「心を燃やせ」的「燃やせ」是「燃える」還是「燃やす」的命令形？', a: '「燃やす」（他動詞）的命令形。' },
    { q: '「勇者ヒンメルならそうした」的「なら」表示什麼？', a: '「如果是…的話、換作是…」（假設、條件）。' },
    { q: '「魔法は…楽しいんだよ」的「んだよ」是什麼的口語？', a: '「のだ」的口語（見口語轉換表）。' },
    { q: '「胸を張る」的字面意思與慣用意思分別是什麼？', a: '字面是「挺起胸膛」，慣用是「抬頭挺胸、問心無愧」。' },
    { q: 'キョンの「やれやれ」與承太郎的「やれやれだぜ」差在哪裡？', a: '「だぜ」讓語氣更男性化、更有力（見口語轉換表的「ぞ／ぜ」）。' },
    { q: '「女のコなんだから気をつけなきゃ」的「なきゃ」是什麼的縮約？', a: '「なければ（ならない）」（見口語轉換表）。' },
    { q: '「愛してる」是哪個形式省略了什麼？', a: '「愛している」省略「い」（ている → てる）。' },
    { q: '「弱いからなめられるんだ」的「なめられる」是什麼形？', a: '「なめる」的被動形。' },
    { q: '「おすわり」是由什麼構成的？', a: '「座る」的名詞形加上美化語「お」。' },
    { q: '「40秒で支度しな」的「しな」是什麼的縮略？', a: '「しなさい」的口語縮略（命令、催促）。' },
    { q: '「見ろ」與「捧げよ」，哪個是口語、哪個是較古風的命令形？', a: '「見ろ」是口語命令形；「捧げよ」是較古風、莊重的命令形。' },
    { q: '「坊やだからさ」句尾的「さ」是什麼？', a: '口語終助詞，表示「理由就是這樣啊」。' },
    { q: '「顔してた」省略了什麼？', a: '「顔をしていた」（省略「を」，ている → てる）。' },
    { q: '「しんでしまう」的口語縮約是什麼？', a: '「死んじゃう」（でしまう → じゃう）。' },
  ],
};

/** @type {Stage[]} */
export const stages = [
  { id: 'stage-0', title: '第 0 階段：N5 復健', lessons: [day1] },
  { id: 'stage-1', title: '第 1 階段：聽力打底', lessons: [] },
  { id: 'stage-2', title: '第 2 階段：口語與動畫日文', lessons: [spoken, quotes] },
  { id: 'stage-3', title: '第 3 階段：N3 到 N1', lessons: [] },
];
